#!/usr/bin/env bash

rm -rf controllers
rm -rf workers

mkdir -p controllers
mkdir -p workers

cd pki
./gen-all

cd ../config
./gen-all

cd ../enc
./gen-dist-encryption-config

cd ..

cp setup-scripts/controller-setup.sh controllers/

cp pki/ca.pem pki/worker*.pem workers/

cp pki/ca.pem pki/ca-key.pem pki/kubernetes-key.pem pki/kubernetes.pem \
    pki/service-account-key.pem pki/service-account.pem \
    controllers/

cp config/worker*.kubeconfig workers/
cp config/kube-proxy.kubeconfig workers/

cp config/admin.kubeconfig config/kube-controller-manager.kubeconfig \
    config/kube-scheduler.kubeconfig \
    controllers/

cp enc/*.yaml controllers/

# terraform validate && terraform apply
