#!/usr/bin/env bash

for instance in worker-0 worker-1; do
  export INTERNAL_IP=$(openstack server show -c addresses -f yaml ${instance} | sed '1,2d;4d' | grep -Po '\d+\.\d+\.\d+\.\d+')
  echo "Copying certs to ${instance} (${INTERNAL_IP})..."
  scp -i ../cloud.key ca.pem ${instance}-key.pem ${instance}.pem ubuntu@${INTERNAL_IP}:~/
done

for instance in controller-0 controller-1; do

  export INTERNAL_IP=$(openstack server show -c addresses -f yaml ${instance} | sed '1,2d;4d' | grep -Po '\d+\.\d+\.\d+\.\d+')
  echo "Copying certs to ${instance} (${INTERNAL_IP})..."

  scp -i ../cloud.key ca.pem ca-key.pem kubernetes-key.pem kubernetes.pem \
      service-account-key.pem service-account.pem \
      ubuntu@${INTERNAL_IP}:~/

done
