#!/usr/bin/env bash

rm *.json
rm *.csr
rm *.pem

./gen-ca
./gen-admin-cert
./gen-kubelet-certs
./gen-cm-client-cert
./gen-proxy-client-cert
./gen-sched-client-cert
./gen-api-server-cert
./gen-svc-account-keypair
