#!/usr/bin/env bash

./remove-all

./gen-ca
./gen-admin-cert
./gen-kubelet-certs
./gen-cm-client-cert
./gen-proxy-client-cert
./gen-sched-client-cert
./gen-api-server-cert
./gen-svc-account-keypair

mkdir -p controller
mkdir -p worker

cp ca.pem worker/
mv worker*.pem worker/

mv ca.pem ca-key.pem kubernetes-key.pem kubernetes.pem service-account-key.pem service-account.pem controller/

