#!/usr/bin/env bash

for n in 0 1; do
cat > worker-${n}-csr.json <<EOF
{
  "CN": "system:node:worker-${n}",
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "C": "NZ",
      "L": "Auckland",
      "O": "system:nodes"
    }
  ]
}
EOF

export EXTERNAL_IP=$(openstack floating ip list -c 'Floating IP Address' -f value)
export INTERNAL_IP=10.240.0.2${n}

echo Generating cert...
echo Instance: worker-${n}
echo External: ${EXTERNAL_IP}
echo Internal: ${INTERNAL_IP}
echo -------------------------

cfssl gencert \
  -loglevel=3 \
  -ca=ca.pem \
  -ca-key=ca-key.pem \
  -config=ca-config.json \
  -hostname=worker-${n},${EXTERNAL_IP},${INTERNAL_IP} \
  -profile=kubernetes \
  worker-${n}-csr.json | cfssljson -bare worker-${n}
done
