#!/usr/bin/env bash

*.kubeconfig
*.kubeconfig

./gen-worker-configs
./gen-proxy-configs
./gen-cm-configs
./gen-sched-configs
./gen-admin-configs

#mv worker*.kubeconfig worker/
#mv kube-proxy.kubeconfig worker/

#mv admin.kubeconfig kube-controller-manager.kubeconfig kube-scheduler.kubeconfig controller/

