#!/usr/bin/env bash

export KUBERNETES_PUBLIC_ADDRESS=$(openstack floating ip list -c 'Floating IP Address' -f value)

for instance in worker-0 worker-1; do
  kubectl config set-cluster kz8s \
    --certificate-authority=../pki/controller/ca.pem \
    --embed-certs=true \
    --server=https://${KUBERNETES_PUBLIC_ADDRESS}:6443 \
    --kubeconfig=${instance}.kubeconfig

  kubectl config set-credentials system:node:${instance} \
    --client-certificate=../pki/worker/${instance}.pem \
    --client-key=../pki/worker/${instance}-key.pem \
    --embed-certs=true \
    --kubeconfig=${instance}.kubeconfig

  kubectl config set-context default \
    --cluster=kz8s \
    --user=system:node:${instance} \
    --kubeconfig=${instance}.kubeconfig

  kubectl config use-context default --kubeconfig=${instance}.kubeconfig
done
